name: Test DIND Shit

on:
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    permissions: write-all
    runs-on: arc-runner-set
    steps:
      - name: Say Hello by Docker
        run: |
          docker run hello-world
